const screen = {
  SIGN_IN: 'SIGN_IN_SCREEN',
  SIGN_UP_STEP_ONE: 'SIGN_UP_STEP_ONE',
  OTP: 'OTP',
  INPUT_GMAIL: 'INPUT_GMAIL',
  OTP_RECOVERY: 'OTP_RECOVERY',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  UPDATE_PERSONAL_INFO: 'UPDATE_PERSONAL_INFO',
  AVATAR_CAMERA: 'AVATAR_CAMERA',
  MAIN_SCREEN: 'MainScreen',
};

export default screen;
