const screen = {
  SIGN_IN: 'SIGN_IN_SCREEN',
  SIGN_UP_STEP_ONE: 'SIGN_UP_STEP_ONE',
  OTP: 'OTP',
  INPUT_GMAIL: 'INPUT_GMAIL',
  OTP_RECOVERY: 'OTP_RECOVERY',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  UPDATE_PERSONAL_INFO: 'UPDATE_PERSONAL_INFO',
  AVATAR_CAMERA: 'AVATAR_CAMERA',
  MAIN_SCREEN: 'MAIN',
  DETAIL_CAR: 'DETAIL_CAR',
  SEARCH: 'SEARCH',
  WALLET_SCREEN: 'WalletScreen',
  INTRO_WALLET_SCREEN: 'IntroWalletScreen',
  CREATE_PASSWORD_WALLET_SCREEN: 'CreatePasswordWalletScreen',
  CREATE_WALLET_SCREEN: 'CreateWalletScreen',
  IMPORT_WALLET_SCREEN: 'ImportWalletScreen',
};

export default screen;
